### PR TITLE
Auto apply code coloring

### PR DESCRIPTION
**Pull request by ArsenijeD**
Make "Envision" theme be applied automatically, once extension is activated.

### CODE REVIEW

**Comment by vermorel** [comment]
Thanks a lot for this contribution. This is a little bit better than the current state of affairs, but it does come with a drawback, the other files (say `.json` files) are not properly rendered anymore due to the `Envision` theme being selected.

For example, with this variant of the extension:

* I have `package.json` opened in VS Code, it's properly rendered (dark) with my default theme `Dark (Visual Studio)`.
* I open `sample.nvn` in VS Code, the theme auto-switch to `Envision`, the Envision code is properly rendered.
* However, the `package.json` is not properly rendered any more.
* When closing `sample.nvn`, the original theme is not restored, which is likely to be quite confusing for users who don't realize that it's a theming issue.

A better solution would probably be to remove the custom theme altogether, and just proceed using the custom scopes introduced for Envision. What do you think?

**Comment by ArsenijeD** [comment]
You're welcome, it's pleasure to be part of this!

That's right, drawback that you mentioned is present. However, it's not introduced with this pull request. I've just checked marketplace version and it's also reproducible there.

I am not sure that I understand your idea fully (for example, part with proceeding with custom scope after Envision theme removal), but there's also one possible solution that I am currently thinking of:

Let's track extension of currently opened file in editor. If it matches `.nvn`, we'll apply `Envision` theme. Other
/wise, we go with `default`. When extension is deactivated, we also go back to default, which I already introduced.

Since this pull request is all about making Evision theme be applied automatically instead of manually, it makes sense to me to leave it as is. Drawback, which is not it's consequence, I would address as a part of another one. It's good to preserve isolation and will be easier to track changes history.

Please let me know about your opinion on this!

**Comment by vermorel** [comment]
If the user can't have side-by-side an Envision file (properly colored) and a JSON file (also properly colored), then unfortunately, this extension is basically not usable.

The _intent_ is to have proper coloring for Envision. The fact that a _custom theme_ gets introduced is accidental. The whole "custom theming" thing might actually be the a mistake that needs to be fixed.

Right now, I can't merge this as it would make the situation worse by "messing" with the theme settings without prior user explicit consent.

**Comment by ArsenijeD** [comment]
Sure, that's a good point. User can get easily confused knowing that he didn't _explicitly_ change theming, but themes are messed up on the other side.

It probably made more sense that we addressed this drawback first, and then on top of it made theme changing be automatic.

Nevertheless, let's go this way:

I'll add fix for this to the _current_ pull request, but for the future, we should describe milestones in a _more details_ which will allow us to split them further in a meaningfull way (of course, if needed).

**Comment by ArsenijeD** [comment]
@vermorel 

Can you please check the behavior now, after introducing the latest change-set?

Problem was that "Envision" theme didn't have necessary `tokenColors` for all the other languages supported by VSCode. 
Once I modified our `envision-theme.json` file to extend `dark-vs.json` file, it allowed us to  have both`sample.nvn` and `package.json` files properly rendered. It's also working if you try to split editor and look at both files at the same time.

Additional note: I added `"$schema": "vscode://schemas/color-theme"` inside `envision-theme.json`, in order to have proper file validation based on VSCode's specification. That resulted in warnings about `background` properties inside `semanticTokenColors` being deprecated. 

Please let me know if you want to remove them, or leave as is for now. Also, let me know if somethings wrong with this change-set.

**Comment by vermorel** [comment]
@ArsenijeD Thanks! I am a bit worried about the maintenance of `dark-vs.json` It's 400 lines of code. Where does it come from? How we supposed to maintain this files when the original theme will evolve?

**Comment by ArsenijeD** [comment]
Yup, that's the tricky part. It's good that you noticed. It's coming from VSCode's github repository. They have implemented their predefined themes (VS Dark, Dark +, Dark Modern, ..) as separated extensions, so I took a look at the way they are linking them.

Maintaining: the only way to achieve it is to sync our local file every time they release changes of their theme. It's not practical, I agree. It's a result of not being able to reference base theme by `name` or `id`. We have to either do it in a way I did, or to copy to whole content to `tokenColors` section of our theme file.

Another possibility that could work (didn't try it out, honestly) is to try referencing the theme file directly, from their repository. That will apply modifications automatically, but will create strong dependency between our and their repo, and also make `internet connection` be mandatory request in order to have syntax highlights supported. Which is also not practical.

**Comment by ArsenijeD** [comment]
Obsolete. Issue resolved in a meantime, with [this](https://github.com/Lokad/vscode-envision/commit/9604304c3fac98d114d627db65fa71c5ebda5386) commit.

**Pull request closed without merging**
