### PR TITLE
Implement semantic token coloring

### PR DESCRIPTION
**Pull request by ArsenijeD**
Make tokens be properly colored without using custom theme or TextMate patterns.

### CODE REVIEW

**Comment by vermorel** [comment]
This looks very cool and promising! Let me testing it, and I will be getting back to you.

**Comment by ArsenijeD** [comment]
Okay, I also think this could work.

**Comment by vermorel** [comment]
@ArsenijeD I confirm that it works!

**Comment by ArsenijeD** [comment]
Very good!

**Pull request merged**
